Add eos_token to FinishReason
Solves issue caused when using TGI:

```
    self.__pydantic_validator__.validate_python(data, self_instance=self)
pydantic_core._pydantic_core.ValidationError: 1 validation error for ChatCompletionResponse
choices.0.finish_reason
  Input should be 'stop', 'length', 'error' or 'tool_calls' [type=enum, input_value='eos_token', input_type=str]

```